#!/usr/bin/env python
# -*- coding:utf-8 -*-
"""
@author: HJK 
@file: music-dl
@time: 2019-01-26

启动器

"""

import os, sys
import gettext

gettext.install("music-dl", "locale")

_srcdir = "%s/" % os.path.dirname(os.path.realpath(__file__))
_filepath = os.path.dirname(sys.argv[0])
sys.path.insert(1, os.path.join(_filepath, _srcdir))

if sys.version_info[0] == 3:
    import music_dl

    if __name__ == "__main__":
        music_dl.main()
else:  # Python 2
    print(_("Python3 Only."))
